// <auto-generated />
namespace Ela_Kai_Pou.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsInOrderAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsInOrderAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202201171829383_IsInOrderAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
